// ============================================================
// גולה עולמי — נתוני מדינות
// ============================================================

const CONTINENTS = {
  'north-america': { nameHe: 'אמריקה הצפונית', color: '#FB923C', dark: '#EA580C' },
  'south-america': { nameHe: 'אמריקה הדרומית', color: '#34D399', dark: '#059669' },
  'europe':        { nameHe: 'אירופה',          color: '#60A5FA', dark: '#2563EB' },
  'africa':        { nameHe: 'אפריקה',          color: '#FBBF24', dark: '#D97706' },
  'asia':          { nameHe: 'אסיה',            color: '#F472B6', dark: '#DB2777' },
  'oceania':       { nameHe: 'אוקיאניה',        color: '#2DD4BF', dark: '#0D9488' },
};

// דגל מתוך קוד ISO 2
function getFlagEmoji(iso2) {
  if (!iso2) return '🏳️';
  return [...iso2.toUpperCase()].map(c =>
    String.fromCodePoint(c.charCodeAt(0) + 127397)
  ).join('');
}

// id = קוד ISO מספרי (תואם TopoJSON world-atlas)
const COUNTRIES = [
  // ── PRIORITY 5 — ידועות מאוד ──
  { id: 376,  iso2: 'IL', nameHe: 'ישראל',              continent: 'asia',          priority: 5 },
  { id: 840,  iso2: 'US', nameHe: 'ארצות הברית',        continent: 'north-america', priority: 5 },
  { id: 643,  iso2: 'RU', nameHe: 'רוסיה',              continent: 'asia',          priority: 5 },
  { id: 156,  iso2: 'CN', nameHe: 'סין',                continent: 'asia',          priority: 5 },
  { id: 76,   iso2: 'BR', nameHe: 'ברזיל',              continent: 'south-america', priority: 5 },
  { id: 818,  iso2: 'EG', nameHe: 'מצרים',              continent: 'africa',        priority: 5 },
  { id: 400,  iso2: 'JO', nameHe: 'ירדן',               continent: 'asia',          priority: 5 },
  { id: 760,  iso2: 'SY', nameHe: 'סוריה',              continent: 'asia',          priority: 5 },
  { id: 422,  iso2: 'LB', nameHe: 'לבנון',              continent: 'asia',          priority: 5 },
  { id: 682,  iso2: 'SA', nameHe: 'ערב הסעודית',        continent: 'asia',          priority: 5 },
  { id: 276,  iso2: 'DE', nameHe: 'גרמניה',             continent: 'europe',        priority: 5 },
  { id: 250,  iso2: 'FR', nameHe: 'צרפת',               continent: 'europe',        priority: 5 },
  { id: 826,  iso2: 'GB', nameHe: 'בריטניה',            continent: 'europe',        priority: 5 },
  { id: 392,  iso2: 'JP', nameHe: 'יפן',                continent: 'asia',          priority: 5 },
  { id: 356,  iso2: 'IN', nameHe: 'הודו',               continent: 'asia',          priority: 5 },
  { id: 36,   iso2: 'AU', nameHe: 'אוסטרליה',           continent: 'oceania',       priority: 5 },
  { id: 124,  iso2: 'CA', nameHe: 'קנדה',               continent: 'north-america', priority: 5 },
  { id: 380,  iso2: 'IT', nameHe: 'איטליה',             continent: 'europe',        priority: 5 },
  { id: 724,  iso2: 'ES', nameHe: 'ספרד',               continent: 'europe',        priority: 5 },
  { id: 484,  iso2: 'MX', nameHe: 'מקסיקו',             continent: 'north-america', priority: 5 },
  // ── PRIORITY 4 — ידועות ──
  { id: 792,  iso2: 'TR', nameHe: 'טורקיה',             continent: 'asia',          priority: 5 },
  { id: 364,  iso2: 'IR', nameHe: 'איראן',              continent: 'asia',          priority: 4 },
  { id: 368,  iso2: 'IQ', nameHe: 'עיראק',              continent: 'asia',          priority: 4 },
  { id: 4,    iso2: 'AF', nameHe: 'אפגניסטן',           continent: 'asia',          priority: 4 },
  { id: 586,  iso2: 'PK', nameHe: 'פקיסטן',             continent: 'asia',          priority: 4 },
  { id: 566,  iso2: 'NG', nameHe: 'ניגריה',             continent: 'africa',        priority: 4 },
  { id: 710,  iso2: 'ZA', nameHe: 'דרום אפריקה',        continent: 'africa',        priority: 4 },
  { id: 32,   iso2: 'AR', nameHe: 'ארגנטינה',           continent: 'south-america', priority: 4 },
  { id: 410,  iso2: 'KR', nameHe: 'קוריאה הדרומית',     continent: 'asia',          priority: 4 },
  { id: 360,  iso2: 'ID', nameHe: 'אינדונזיה',          continent: 'asia',          priority: 4 },
  { id: 528,  iso2: 'NL', nameHe: 'הולנד',              continent: 'europe',        priority: 4 },
  { id: 56,   iso2: 'BE', nameHe: 'בלגיה',              continent: 'europe',        priority: 4 },
  { id: 752,  iso2: 'SE', nameHe: 'שוודיה',             continent: 'europe',        priority: 5 },
  { id: 578,  iso2: 'NO', nameHe: 'נורווגיה',           continent: 'europe',        priority: 4 },
  { id: 756,  iso2: 'CH', nameHe: 'שווייץ',             continent: 'europe',        priority: 4 },
  { id: 40,   iso2: 'AT', nameHe: 'אוסטריה',            continent: 'europe',        priority: 4 },
  { id: 620,  iso2: 'PT', nameHe: 'פורטוגל',            continent: 'europe',        priority: 5 },
  { id: 300,  iso2: 'GR', nameHe: 'יוון',               continent: 'europe',        priority: 4 },
  { id: 616,  iso2: 'PL', nameHe: 'פולין',              continent: 'europe',        priority: 4 },
  { id: 804,  iso2: 'UA', nameHe: 'אוקראינה',           continent: 'europe',        priority: 4 },
  { id: 764,  iso2: 'TH', nameHe: 'תאילנד',             continent: 'asia',          priority: 4 },
  { id: 704,  iso2: 'VN', nameHe: 'וייטנאם',            continent: 'asia',          priority: 4 },
  { id: 608,  iso2: 'PH', nameHe: 'הפיליפינים',         continent: 'asia',          priority: 4 },
  { id: 458,  iso2: 'MY', nameHe: 'מלזיה',              continent: 'asia',          priority: 4 },
  { id: 404,  iso2: 'KE', nameHe: 'קניה',               continent: 'africa',        priority: 4 },
  { id: 231,  iso2: 'ET', nameHe: 'אתיופיה',            continent: 'africa',        priority: 4 },
  { id: 12,   iso2: 'DZ', nameHe: "אלג'יריה",           continent: 'africa',        priority: 4 },
  { id: 504,  iso2: 'MA', nameHe: 'מרוקו',              continent: 'africa',        priority: 4 },
  { id: 192,  iso2: 'CU', nameHe: 'קובה',               continent: 'north-america', priority: 4 },
  { id: 170,  iso2: 'CO', nameHe: 'קולומביה',           continent: 'south-america', priority: 4 },
  { id: 152,  iso2: 'CL', nameHe: "צ'ילה",              continent: 'south-america', priority: 4 },
  { id: 604,  iso2: 'PE', nameHe: 'פרו',                continent: 'south-america', priority: 4 },
  { id: 554,  iso2: 'NZ', nameHe: 'ניו זילנד',          continent: 'oceania',       priority: 4 },
  { id: 414,  iso2: 'KW', nameHe: 'כווית',              continent: 'asia',          priority: 4 },
  { id: 784,  iso2: 'AE', nameHe: 'איחוד האמירויות',    continent: 'asia',          priority: 4 },
  { id: 634,  iso2: 'QA', nameHe: 'קטר',                continent: 'asia',          priority: 4 },
  // ── PRIORITY 3 — מוכרות בינוני ──
  { id: 48,   iso2: 'BH', nameHe: 'בחריין',             continent: 'asia',          priority: 3 },
  { id: 512,  iso2: 'OM', nameHe: 'עומאן',              continent: 'asia',          priority: 3 },
  { id: 887,  iso2: 'YE', nameHe: 'תימן',               continent: 'asia',          priority: 3 },
  { id: 860,  iso2: 'UZ', nameHe: 'אוזבקיסטן',          continent: 'asia',          priority: 3 },
  { id: 398,  iso2: 'KZ', nameHe: 'קזחסטן',             continent: 'asia',          priority: 3 },
  { id: 104,  iso2: 'MM', nameHe: 'מיאנמר',             continent: 'asia',          priority: 3 },
  { id: 116,  iso2: 'KH', nameHe: 'קמבודיה',            continent: 'asia',          priority: 3 },
  { id: 418,  iso2: 'LA', nameHe: 'לאוס',               continent: 'asia',          priority: 3 },
  { id: 50,   iso2: 'BD', nameHe: 'בנגלדש',             continent: 'asia',          priority: 3 },
  { id: 144,  iso2: 'LK', nameHe: 'סרי לנקה',           continent: 'asia',          priority: 3 },
  { id: 524,  iso2: 'NP', nameHe: 'נפאל',               continent: 'asia',          priority: 3 },
  { id: 702,  iso2: 'SG', nameHe: 'סינגפור',            continent: 'asia',          priority: 3 },
  { id: 408,  iso2: 'KP', nameHe: 'קוריאה הצפונית',     continent: 'asia',          priority: 3 },
  { id: 496,  iso2: 'MN', nameHe: 'מונגוליה',           continent: 'asia',          priority: 3 },
  { id: 268,  iso2: 'GE', nameHe: 'גאורגיה',            continent: 'asia',          priority: 3 },
  { id: 51,   iso2: 'AM', nameHe: 'ארמניה',             continent: 'asia',          priority: 3 },
  { id: 31,   iso2: 'AZ', nameHe: "אזרבייג'ן",          continent: 'asia',          priority: 3 },
  { id: 642,  iso2: 'RO', nameHe: 'רומניה',             continent: 'europe',        priority: 3 },
  { id: 348,  iso2: 'HU', nameHe: 'הונגריה',            continent: 'europe',        priority: 4 },
  { id: 203,  iso2: 'CZ', nameHe: "צ'כיה",              continent: 'europe',        priority: 3 },
  { id: 703,  iso2: 'SK', nameHe: 'סלובקיה',            continent: 'europe',        priority: 3 },
  { id: 191,  iso2: 'HR', nameHe: 'קרואטיה',            continent: 'europe',        priority: 4 },
  { id: 688,  iso2: 'RS', nameHe: 'סרביה',              continent: 'europe',        priority: 3 },
  { id: 100,  iso2: 'BG', nameHe: 'בולגריה',            continent: 'europe',        priority: 3 },
  { id: 208,  iso2: 'DK', nameHe: 'דנמרק',              continent: 'europe',        priority: 4 },
  { id: 246,  iso2: 'FI', nameHe: 'פינלנד',             continent: 'europe',        priority: 4 },
  { id: 372,  iso2: 'IE', nameHe: 'אירלנד',             continent: 'europe',        priority: 3 },
  { id: 288,  iso2: 'GH', nameHe: 'גנה',                continent: 'africa',        priority: 3 },
  { id: 834,  iso2: 'TZ', nameHe: 'טנזניה',             continent: 'africa',        priority: 3 },
  { id: 434,  iso2: 'LY', nameHe: 'לוב',                continent: 'africa',        priority: 3 },
  { id: 788,  iso2: 'TN', nameHe: 'תוניסיה',            continent: 'africa',        priority: 3 },
  { id: 508,  iso2: 'MZ', nameHe: 'מוזמביק',            continent: 'africa',        priority: 3 },
  { id: 24,   iso2: 'AO', nameHe: 'אנגולה',             continent: 'africa',        priority: 3 },
  { id: 729,  iso2: 'SD', nameHe: 'סודן',               continent: 'africa',        priority: 3 },
  { id: 862,  iso2: 'VE', nameHe: 'ונצואלה',            continent: 'south-america', priority: 3 },
  { id: 218,  iso2: 'EC', nameHe: 'אקוודור',            continent: 'south-america', priority: 3 },
  { id: 68,   iso2: 'BO', nameHe: 'בוליביה',            continent: 'south-america', priority: 3 },
  { id: 600,  iso2: 'PY', nameHe: 'פרגוואי',            continent: 'south-america', priority: 3 },
  { id: 858,  iso2: 'UY', nameHe: 'אורוגוואי',          continent: 'south-america', priority: 3 },
  { id: 320,  iso2: 'GT', nameHe: 'גואטמלה',            continent: 'north-america', priority: 3 },
  { id: 340,  iso2: 'HN', nameHe: 'הונדורס',            continent: 'north-america', priority: 3 },
  { id: 591,  iso2: 'PA', nameHe: 'פנמה',               continent: 'north-america', priority: 3 },
  { id: 188,  iso2: 'CR', nameHe: 'קוסטה ריקה',         continent: 'north-america', priority: 3 },
  { id: 598,  iso2: 'PG', nameHe: 'פפואה גינאה החדשה',  continent: 'oceania',       priority: 3 },
  // ── PRIORITY 2 — פחות מוכרות ──
  { id: 762,  iso2: 'TJ', nameHe: "טג'יקיסטן",          continent: 'asia',          priority: 2 },
  { id: 795,  iso2: 'TM', nameHe: 'טורקמניסטן',         continent: 'asia',          priority: 2 },
  { id: 417,  iso2: 'KG', nameHe: 'קירגיזסטן',          continent: 'asia',          priority: 2 },
  { id: 96,   iso2: 'BN', nameHe: 'ברוניי',             continent: 'asia',          priority: 2 },
  { id: 626,  iso2: 'TL', nameHe: 'טימור-לסטה',         continent: 'asia',          priority: 2 },
  { id: 64,   iso2: 'BT', nameHe: 'בהוטן',              continent: 'asia',          priority: 2 },
  { id: 112,  iso2: 'BY', nameHe: 'בלארוס',             continent: 'europe',        priority: 2 },
  { id: 428,  iso2: 'LV', nameHe: 'לטביה',              continent: 'europe',        priority: 2 },
  { id: 440,  iso2: 'LT', nameHe: 'ליטא',               continent: 'europe',        priority: 2 },
  { id: 233,  iso2: 'EE', nameHe: 'אסטוניה',            continent: 'europe',        priority: 2 },
  { id: 807,  iso2: 'MK', nameHe: 'צפון מקדוניה',       continent: 'europe',        priority: 2 },
  { id: 8,    iso2: 'AL', nameHe: 'אלבניה',             continent: 'europe',        priority: 2 },
  { id: 70,   iso2: 'BA', nameHe: 'בוסניה',             continent: 'europe',        priority: 2 },
  { id: 499,  iso2: 'ME', nameHe: 'מונטנגרו',           continent: 'europe',        priority: 2 },
  { id: 705,  iso2: 'SI', nameHe: 'סלובניה',            continent: 'europe',        priority: 2 },
  { id: 352,  iso2: 'IS', nameHe: 'איסלנד',             continent: 'europe',        priority: 2 },
  { id: 442,  iso2: 'LU', nameHe: 'לוקסמבורג',          continent: 'europe',        priority: 2 },
  { id: 196,  iso2: 'CY', nameHe: 'קפריסין',            continent: 'europe',        priority: 2 },
  { id: 498,  iso2: 'MD', nameHe: 'מולדובה',            continent: 'europe',        priority: 2 },
  { id: 384,  iso2: 'CI', nameHe: 'חוף השנהב',          continent: 'africa',        priority: 2 },
  { id: 120,  iso2: 'CM', nameHe: 'קמרון',              continent: 'africa',        priority: 2 },
  { id: 180,  iso2: 'CD', nameHe: 'קונגו קינשסה',        continent: 'africa',        priority: 2 },
  { id: 466,  iso2: 'ML', nameHe: 'מאלי',               continent: 'africa',        priority: 2 },
  { id: 854,  iso2: 'BF', nameHe: 'בורקינה פאסו',       continent: 'africa',        priority: 2 },
  { id: 686,  iso2: 'SN', nameHe: 'סנגל',               continent: 'africa',        priority: 2 },
  { id: 562,  iso2: 'NE', nameHe: "ניז'ר",              continent: 'africa',        priority: 2 },
  { id: 148,  iso2: 'TD', nameHe: "צ'אד",               continent: 'africa',        priority: 2 },
  { id: 706,  iso2: 'SO', nameHe: 'סומליה',             continent: 'africa',        priority: 2 },
  { id: 450,  iso2: 'MG', nameHe: 'מדגסקר',             continent: 'africa',        priority: 2 },
  { id: 894,  iso2: 'ZM', nameHe: 'זמביה',              continent: 'africa',        priority: 2 },
  { id: 716,  iso2: 'ZW', nameHe: 'זימבבואה',           continent: 'africa',        priority: 2 },
  { id: 800,  iso2: 'UG', nameHe: 'אוגנדה',             continent: 'africa',        priority: 2 },
  { id: 646,  iso2: 'RW', nameHe: 'רואנדה',             continent: 'africa',        priority: 2 },
  { id: 454,  iso2: 'MW', nameHe: 'מלאווי',             continent: 'africa',        priority: 2 },
  { id: 516,  iso2: 'NA', nameHe: 'נמיביה',             continent: 'africa',        priority: 2 },
  { id: 72,   iso2: 'BW', nameHe: 'בוצואנה',            continent: 'africa',        priority: 2 },
  { id: 478,  iso2: 'MR', nameHe: 'מאוריטניה',          continent: 'africa',        priority: 2 },
  { id: 558,  iso2: 'NI', nameHe: 'ניקרגואה',           continent: 'north-america', priority: 2 },
  { id: 222,  iso2: 'SV', nameHe: 'אל סלוודור',         continent: 'north-america', priority: 2 },
  { id: 84,   iso2: 'BZ', nameHe: 'בליז',               continent: 'north-america', priority: 2 },
  { id: 214,  iso2: 'DO', nameHe: 'הרפובליקה הדומיניקנית', continent: 'north-america', priority: 2 },
  { id: 332,  iso2: 'HT', nameHe: 'האיטי',              continent: 'north-america', priority: 2 },
  { id: 388,  iso2: 'JM', nameHe: "ג'מייקה",            continent: 'north-america', priority: 2 },
  { id: 740,  iso2: 'SR', nameHe: 'סורינאם',            continent: 'south-america', priority: 2 },
  { id: 328,  iso2: 'GY', nameHe: 'גיאנה',              continent: 'south-america', priority: 2 },
  { id: 242,  iso2: 'FJ', nameHe: "פיג'י",              continent: 'oceania',       priority: 2 },
  // ── PRIORITY 1 — אזוטריות ──
  { id: 108,  iso2: 'BI', nameHe: 'בורונדי',            continent: 'africa',        priority: 1 },
  { id: 226,  iso2: 'GQ', nameHe: 'גינאה המשוונית',     continent: 'africa',        priority: 1 },
  { id: 266,  iso2: 'GA', nameHe: 'גבון',               continent: 'africa',        priority: 1 },
  { id: 178,  iso2: 'CG', nameHe: 'קונגו ברזוויל',      continent: 'africa',        priority: 1 },
  { id: 426,  iso2: 'LS', nameHe: 'לסוטו',              continent: 'africa',        priority: 1 },
  { id: 232,  iso2: 'ER', nameHe: 'אריתריאה',           continent: 'africa',        priority: 1 },
  { id: 262,  iso2: 'DJ', nameHe: "ג'יבוטי",            continent: 'africa',        priority: 1 },
  { id: 324,  iso2: 'GN', nameHe: 'גינאה',              continent: 'africa',        priority: 1 },
  { id: 624,  iso2: 'GW', nameHe: 'גינאה-ביסאו',        continent: 'africa',        priority: 1 },
  { id: 694,  iso2: 'SL', nameHe: 'סיירה לאונה',        continent: 'africa',        priority: 1 },
  { id: 430,  iso2: 'LR', nameHe: 'ליבריה',             continent: 'africa',        priority: 1 },
  { id: 270,  iso2: 'GM', nameHe: 'גמביה',              continent: 'africa',        priority: 1 },
  { id: 728,  iso2: 'SS', nameHe: 'דרום סודן',          continent: 'africa',        priority: 1 },
  { id: 748,  iso2: 'SZ', nameHe: 'אסוואטיני',          continent: 'africa',        priority: 1 },
  { id: 140,  iso2: 'CF', nameHe: 'רפובליקה אפריקאית המרכזית', continent: 'africa', priority: 1 },
  { id: 768,  iso2: 'TG', nameHe: 'טוגו',               continent: 'africa',        priority: 1 },
  { id: 204,  iso2: 'BJ', nameHe: 'בנין',               continent: 'africa',        priority: 1 },
  { id: 674,  iso2: 'SM', nameHe: 'סן מרינו',           continent: 'europe',        priority: 1 },
  { id: 20,   iso2: 'AD', nameHe: 'אנדורה',             continent: 'europe',        priority: 1 },
  { id: 585,  iso2: 'PW', nameHe: 'פלאו',               continent: 'oceania',       priority: 1 },
  { id: 583,  iso2: 'FM', nameHe: 'מיקרונזיה',          continent: 'oceania',       priority: 1 },
  { id: 520,  iso2: 'NR', nameHe: 'נאורו',              continent: 'oceania',       priority: 1 },
  { id: 882,  iso2: 'WS', nameHe: 'סמואה',              continent: 'oceania',       priority: 1 },
  { id: 776,  iso2: 'TO', nameHe: 'טונגה',              continent: 'oceania',       priority: 1 },
  { id: 548,  iso2: 'VU', nameHe: 'ונואטו',             continent: 'oceania',       priority: 1 },
  { id: 90,   iso2: 'SB', nameHe: 'איי שלמה',           continent: 'oceania',       priority: 1 },
];

// אבני דרך לפרסים
const PRIZES = [
  { points: 500,   achievement: 'נוסע סקרן',    prize: 'ממתק',                  emoji: '🍬' },
  { points: 1500,  achievement: 'מגלה דרכים',   prize: 'קולה',                  emoji: '🥤' },
  { points: 4000,  achievement: 'אמן המפות',    prize: 'מקדונלדס',              emoji: '🍔' },
  { points: 8000,  achievement: 'שגריר יבשות',  prize: 'חבילת סוכריות גומי',   emoji: '🐻' },
  { points: 15000, achievement: 'גיבור העולם',  prize: 'מה שתבחרו עד 100 ש"ח', emoji: '🎁' },
];

// רמות קושי — כל רמה = priority בלעדי (לא מצטבר)
const LEVELS = {
  easy:   { nameHe: 'קלה',     minPriority: 5, maxPriority: 5, points: 10, passThreshold: 8, masteryBonus: 20,  unlockAt: 0  },
  medium: { nameHe: 'בינונית', minPriority: 4, maxPriority: 4, points: 15, passThreshold: 7, masteryBonus: 35,  unlockAt: 6  },
  hard:   { nameHe: 'קשה',     minPriority: 3, maxPriority: 3, points: 20, passThreshold: 6, masteryBonus: 60,  unlockAt: 20 },
  master: { nameHe: 'מאסטר',   minPriority: 1, maxPriority: 2, points: 25, passThreshold: 6, masteryBonus: 100, unlockAt: 60 },
};

// ── Badge definitions ──────────────────────────────────────────
const LEVEL_BADGES = {
  easy:   { key: 'badge_easy',   emoji: '🗺️', name: 'חוקר',  starsNeeded: 12 },
  medium: { key: 'badge_medium', emoji: '🌍', name: 'מגלה',  starsNeeded: 12 },
  hard:   { key: 'badge_hard',   emoji: '🏆', name: 'מומחה', starsNeeded: 12 },
  master: { key: 'badge_master', emoji: '👑', name: 'אלוף',  starsNeeded: 12 },
};
const DISCOVERY_BADGES = [
  { key: 'badge_scout', emoji: '🔍', name: 'גלאי', countriesNeeded: 50  },
  { key: 'badge_world', emoji: '🌐', name: 'עולם', countriesNeeded: 100 },
];

// ── נתוני בירות: { capital: עברית, capitalCoords: [lon, lat] } ────
const CAPITALS = {
  // Priority 5
  376: { capital: 'ירושלים',          capitalCoords: [35.22, 31.77]  },
  840: { capital: 'וושינגטון ד.ס.',  capitalCoords: [-77.01, 38.89] },
  643: { capital: 'מוסקבה',           capitalCoords: [37.62, 55.75]  },
  156: { capital: "בייג'ינג",         capitalCoords: [116.38, 39.91] },
  76:  { capital: 'ברזיליה',          capitalCoords: [-47.93, -15.78]},
  818: { capital: 'קהיר',             capitalCoords: [31.24, 30.04]  },
  400: { capital: 'עמאן',             capitalCoords: [35.93, 31.95]  },
  760: { capital: 'דמשק',             capitalCoords: [36.29, 33.51]  },
  422: { capital: 'ביירות',           capitalCoords: [35.50, 33.89]  },
  682: { capital: 'ריאד',             capitalCoords: [46.68, 24.69]  },
  276: { capital: 'ברלין',            capitalCoords: [13.41, 52.52]  },
  250: { capital: 'פריז',             capitalCoords: [2.35,  48.86]  },
  826: { capital: 'לונדון',           capitalCoords: [-0.13, 51.51]  },
  392: { capital: 'טוקיו',            capitalCoords: [139.69, 35.69] },
  356: { capital: 'ניו דלהי',         capitalCoords: [77.21, 28.61]  },
  36:  { capital: 'קנברה',            capitalCoords: [149.13,-35.28] },
  124: { capital: 'אוטווה',           capitalCoords: [-75.70, 45.42] },
  380: { capital: 'רומא',             capitalCoords: [12.49, 41.90]  },
  724: { capital: 'מדריד',            capitalCoords: [-3.70, 40.42]  },
  484: { capital: 'מקסיקו סיטי',      capitalCoords: [-99.13, 19.43] },
  // Priority 4-5
  792: { capital: 'אנקרה',            capitalCoords: [32.86, 39.93]  },
  364: { capital: 'טהרן',             capitalCoords: [51.39, 35.69]  },
  368: { capital: 'בגדד',             capitalCoords: [44.39, 33.34]  },
  4:   { capital: 'קאבול',            capitalCoords: [69.18, 34.52]  },
  586: { capital: 'איסלאמאבד',        capitalCoords: [73.05, 33.72]  },
  566: { capital: "אבוג'ה",           capitalCoords: [7.49,   9.06]  },
  710: { capital: 'פרטוריה',          capitalCoords: [28.19, -25.75] },
  32:  { capital: 'בואנוס איירס',     capitalCoords: [-58.38,-34.60] },
  410: { capital: 'סיאול',            capitalCoords: [126.98, 37.57] },
  360: { capital: "ג'קרטה",           capitalCoords: [106.85,  -6.21]},
  528: { capital: 'אמסטרדם',          capitalCoords: [4.90,  52.37]  },
  56:  { capital: 'בריסל',            capitalCoords: [4.35,  50.85]  },
  752: { capital: 'שטוקהולם',         capitalCoords: [18.07, 59.33]  },
  578: { capital: 'אוסלו',            capitalCoords: [10.75, 59.91]  },
  756: { capital: 'ברן',              capitalCoords: [7.45,  46.95]  },
  40:  { capital: 'וינה',             capitalCoords: [16.37, 48.21]  },
  620: { capital: 'ליסבון',           capitalCoords: [-9.14, 38.72]  },
  300: { capital: 'אתונה',            capitalCoords: [23.73, 37.98]  },
  616: { capital: 'ורשה',             capitalCoords: [21.01, 52.23]  },
  804: { capital: 'קייב',             capitalCoords: [30.52, 50.45]  },
  764: { capital: 'בנגקוק',           capitalCoords: [100.50, 13.75] },
  704: { capital: 'האנוי',            capitalCoords: [105.85, 21.03] },
  608: { capital: 'מנילה',            capitalCoords: [120.97, 14.60] },
  458: { capital: 'קואלה לומפור',     capitalCoords: [101.69,  3.14] },
  404: { capital: 'נירובי',           capitalCoords: [36.82,  -1.29] },
  231: { capital: 'אדיס אבבה',        capitalCoords: [38.74,   9.03] },
  12:  { capital: "אלג'יר",           capitalCoords: [3.05,  36.74]  },
  504: { capital: 'רבאט',             capitalCoords: [-6.83, 34.02]  },
  192: { capital: 'הוואנה',           capitalCoords: [-82.37, 23.13] },
  170: { capital: 'בוגוטה',           capitalCoords: [-74.08,  4.71] },
  152: { capital: 'סנטיאגו',          capitalCoords: [-70.67,-33.45] },
  604: { capital: 'לימה',             capitalCoords: [-77.04,-12.05] },
  554: { capital: 'וולינגטון',        capitalCoords: [174.78,-41.29] },
  414: { capital: 'כווית סיטי',       capitalCoords: [47.98,  29.37] },
  784: { capital: 'אבו דאבי',         capitalCoords: [54.37,  24.47] },
  634: { capital: 'דוחה',             capitalCoords: [51.53,  25.29] },
  348: { capital: 'בודפשט',           capitalCoords: [19.04,  47.50] },
  191: { capital: 'זגרב',             capitalCoords: [15.98,  45.81] },
  208: { capital: 'קופנהגן',          capitalCoords: [12.57,  55.68] },
  246: { capital: 'הלסינקי',          capitalCoords: [24.94,  60.17] },
  372: { capital: 'דבלין',            capitalCoords: [-6.27,  53.33] },
  // Priority 3
  48:  { capital: 'מנאמה',            capitalCoords: [50.59,  26.21] },
  512: { capital: 'מסקט',             capitalCoords: [58.59,  23.59] },
  887: { capital: "סנעא'",            capitalCoords: [44.21,  15.35] },
  860: { capital: 'טשקנט',            capitalCoords: [69.27,  41.30] },
  398: { capital: 'אסטנה',            capitalCoords: [71.45,  51.18] },
  104: { capital: 'נייפידו',          capitalCoords: [96.13,  19.74] },
  116: { capital: 'פנום פן',          capitalCoords: [104.92, 11.57] },
  418: { capital: 'ויינטיאן',         capitalCoords: [102.60, 17.97] },
  50:  { capital: 'דאקה',             capitalCoords: [90.41,  23.72] },
  144: { capital: 'קולומבו',          capitalCoords: [79.85,   6.93] },
  524: { capital: 'קטמנדו',           capitalCoords: [85.32,  27.72] },
  702: { capital: 'סינגפור',          capitalCoords: [103.82,  1.35] },
  408: { capital: 'פיונגיאנג',        capitalCoords: [125.73, 39.03] },
  496: { capital: 'אולן בטור',        capitalCoords: [106.91, 47.91] },
  268: { capital: 'טביליסי',          capitalCoords: [44.83,  41.69] },
  51:  { capital: 'ירוואן',           capitalCoords: [44.51,  40.18] },
  31:  { capital: 'באקו',             capitalCoords: [49.87,  40.41] },
  642: { capital: 'בוקרשט',           capitalCoords: [26.10,  44.44] },
  203: { capital: 'פראג',             capitalCoords: [14.44,  50.07] },
  703: { capital: 'ברטיסלאווה',       capitalCoords: [17.11,  48.14] },
  688: { capital: 'בלגרד',            capitalCoords: [20.46,  44.81] },
  100: { capital: 'סופיה',            capitalCoords: [23.32,  42.70] },
  288: { capital: 'אקרה',             capitalCoords: [-0.19,   5.56] },
  834: { capital: 'דודומה',           capitalCoords: [35.74,  -6.17] },
  434: { capital: 'טריפולי',          capitalCoords: [13.17,  32.90] },
  788: { capital: 'תוניס',            capitalCoords: [10.18,  36.82] },
  508: { capital: 'מאפוטו',           capitalCoords: [32.59, -25.96] },
  24:  { capital: 'לואנדה',           capitalCoords: [13.23,  -8.84] },
  729: { capital: 'חרטום',            capitalCoords: [32.53,  15.55] },
  862: { capital: 'קראקס',            capitalCoords: [-66.92, 10.49] },
  218: { capital: 'קיטו',             capitalCoords: [-78.50,  -0.23]},
  68:  { capital: "לה פאס",           capitalCoords: [-68.15,-16.50] },
  600: { capital: 'אסונסיון',         capitalCoords: [-57.64,-25.29] },
  858: { capital: 'מונטווידאו',       capitalCoords: [-56.17,-34.90] },
  320: { capital: 'גואטמלה סיטי',     capitalCoords: [-90.52, 14.64] },
  340: { capital: 'טגוסיגלפה',        capitalCoords: [-87.22, 14.10] },
  591: { capital: 'פנמה סיטי',        capitalCoords: [-79.53,  8.99] },
  188: { capital: 'סן חוסה',          capitalCoords: [-84.09,  9.93] },
  598: { capital: 'פורט מורסבי',      capitalCoords: [147.19,  -9.44]},
  // Priority 2
  762: { capital: 'דושנבה',           capitalCoords: [68.77,  38.56] },
  795: { capital: 'עשגבאט',           capitalCoords: [58.38,  37.95] },
  417: { capital: 'ביאשקק',           capitalCoords: [74.59,  42.87] },
  96:  { capital: 'בנדר סרי בגוואן',  capitalCoords: [114.94,  4.94] },
  626: { capital: 'דילי',             capitalCoords: [125.58,  -8.56]},
  64:  { capital: 'תימפו',            capitalCoords: [89.64,  27.47] },
  112: { capital: 'מינסק',            capitalCoords: [27.57,  53.90] },
  428: { capital: 'ריגה',             capitalCoords: [24.11,  56.95] },
  440: { capital: 'וילנה',            capitalCoords: [25.28,  54.69] },
  233: { capital: 'טאלין',            capitalCoords: [24.74,  59.44] },
  807: { capital: 'סקופיה',           capitalCoords: [21.43,  42.00] },
  8:   { capital: 'טירנה',            capitalCoords: [19.83,  41.33] },
  70:  { capital: 'סרייבו',           capitalCoords: [18.39,  43.86] },
  499: { capital: 'פודגוריצה',        capitalCoords: [19.26,  42.44] },
  705: { capital: 'לובליאנה',         capitalCoords: [14.51,  46.05] },
  352: { capital: 'רייקיאוויק',       capitalCoords: [-21.90, 64.15] },
  442: { capital: 'לוקסמבורג',        capitalCoords: [6.13,   49.61] },
  196: { capital: 'ניקוסיה',          capitalCoords: [33.36,  35.17] },
  498: { capital: 'קישינב',           capitalCoords: [28.86,  47.00] },
  384: { capital: "אביג'אן",          capitalCoords: [-4.03,   5.36] },
  120: { capital: 'יאונדה',           capitalCoords: [11.52,   3.87] },
  180: { capital: 'קינשסה',           capitalCoords: [15.32,  -4.32] },
  466: { capital: 'במאקו',            capitalCoords: [-7.99,  12.65] },
  854: { capital: 'וואגאדוגו',        capitalCoords: [-1.52,  12.37] },
  686: { capital: 'דאקאר',            capitalCoords: [-17.44, 14.69] },
  562: { capital: 'ניאמיי',           capitalCoords: [2.11,   13.51] },
  148: { capital: "נג'מינה",          capitalCoords: [15.04,  12.11] },
  706: { capital: 'מוגדישו',          capitalCoords: [45.34,   2.05] },
  450: { capital: 'אנטנאנריבו',       capitalCoords: [47.52, -18.91] },
  894: { capital: 'לוסקה',            capitalCoords: [28.31, -15.42] },
  716: { capital: 'הרארה',            capitalCoords: [31.05, -17.83] },
  800: { capital: 'קמפאלה',           capitalCoords: [32.58,   0.32] },
  646: { capital: 'קיגלי',            capitalCoords: [30.06,  -1.95] },
  454: { capital: 'לילונגווה',        capitalCoords: [33.78, -13.97] },
  516: { capital: 'וינדהוק',          capitalCoords: [17.08, -22.56] },
  72:  { capital: 'גאבורון',          capitalCoords: [25.91, -24.65] },
  478: { capital: 'נואקשוט',          capitalCoords: [-15.98, 18.08] },
  558: { capital: 'מנגואה',           capitalCoords: [-86.29, 12.14] },
  222: { capital: 'סן סלוודור',       capitalCoords: [-89.20, 13.70] },
  84:  { capital: 'בלמופן',           capitalCoords: [-88.77, 17.25] },
  214: { capital: 'סנטו דומינגו',     capitalCoords: [-69.90, 18.48] },
  332: { capital: 'פורט או פרנס',     capitalCoords: [-72.34, 18.54] },
  388: { capital: 'קינגסטון',         capitalCoords: [-76.79, 17.99] },
  740: { capital: 'פרמריבו',          capitalCoords: [-55.17,  5.87] },
  328: { capital: "ג'ורג'טאון",       capitalCoords: [-58.16,  6.80] },
  242: { capital: 'סובה',             capitalCoords: [178.44,-18.14] },
  // Priority 1
  108: { capital: "בוג'מבורה",        capitalCoords: [29.36,  -3.38] },
  226: { capital: 'מלאבו',            capitalCoords: [8.78,    3.75] },
  266: { capital: 'ליברוויל',         capitalCoords: [9.45,    0.39] },
  178: { capital: 'ברזוויל',          capitalCoords: [15.28,  -4.27] },
  426: { capital: 'מסרו',             capitalCoords: [27.48, -29.32] },
  232: { capital: 'אסמרה',            capitalCoords: [38.93,  15.34] },
  262: { capital: "ג'יבוטי סיטי",    capitalCoords: [43.14,  11.59] },
  324: { capital: 'קונקרי',           capitalCoords: [-13.71,  9.54] },
  624: { capital: 'ביסאו',            capitalCoords: [-15.60, 11.86] },
  694: { capital: 'פריטאון',          capitalCoords: [-13.23,  8.49] },
  430: { capital: 'מונרוביה',         capitalCoords: [-10.80,  6.30] },
  270: { capital: "בנג'ול",           capitalCoords: [-16.58, 13.45] },
  728: { capital: "ג'ובה",            capitalCoords: [31.57,   4.85] },
  748: { capital: 'מבאבנה',           capitalCoords: [31.13, -26.32] },
  140: { capital: 'בנגי',             capitalCoords: [18.56,   4.37] },
  768: { capital: 'לומה',             capitalCoords: [1.22,    6.14] },
  204: { capital: 'פורטו נובו',       capitalCoords: [2.62,    6.37] },
  674: { capital: 'סן מרינו',         capitalCoords: [12.44,  43.94] },
  20:  { capital: 'אנדורה לה וייה',  capitalCoords: [1.52,   42.51] },
  585: { capital: 'נגרולמוד',         capitalCoords: [134.48,  7.50] },
  583: { capital: 'פליקיר',           capitalCoords: [158.18,  6.91] },
  520: { capital: 'יארן',             capitalCoords: [166.92, -0.54] },
  882: { capital: 'אפיה',             capitalCoords: [-171.77,-13.83]},
  776: { capital: 'נוקואלופה',        capitalCoords: [-175.22,-21.14]},
  548: { capital: 'פורט וילה',        capitalCoords: [168.32, -17.73]},
  90:  { capital: 'הוניארה',          capitalCoords: [159.95,  -9.43]},
};

// עזרים
function getCountryById(id) {
  const numId = Number(id);
  return COUNTRIES.find(c => c.id === numId);
}

function getCountriesByLevel(level, continent = 'all') {
  const cfg = LEVELS[level];
  return COUNTRIES.filter(c => {
    const inLevel = c.priority >= cfg.minPriority && c.priority <= cfg.maxPriority;
    const inContinent = continent === 'all' || c.continent === continent;
    return inLevel && inContinent;
  });
}

function getWrongChoices(correct, pool, count = 3) {
  // prefer same continent
  let sameContinent = pool.filter(c => c.id !== correct.id && c.continent === correct.continent);
  let diff = pool.filter(c => c.id !== correct.id && c.continent !== correct.continent);
  // shuffle
  sameContinent = shuffle(sameContinent);
  diff = shuffle(diff);
  const candidates = [...sameContinent, ...diff];
  return candidates.slice(0, count);
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
